title: Atharva Bhosale
description: Mechanical engineering student at IIT Tirupati building robots with ROS2, Python and C++.
# If you rename the repo to batharva.github.io, set baseurl to ""
baseurl: "/portfolio2"
url: "https://batharva.github.io"
permalink: /blog/:title/
future: true
collections:
  projects:
    output: false
exclude: [README.md, LICENSE]
